stages:
  - build
  - test

image: python:latest

services:
  - mongo

cache:
  paths:
    - api-application/tests/*
    - venv/


before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt


build-code-job:
  stage: build
  script:
    - echo "Check the python version, then build some Python project files:"
    - apt-get -qq update && apt-get -qq install -y python
    - apt-get -qq update
    - apt-get -qq install -y python python-virtualenv python-pip


test-sensor:
  stage: test
  script:
    - echo "TESTING SOME SENSOR TESTS"
    - python -m unittest discover -s ./api-application/tests/sensors_controller/


test-security:
  stage: test
  script:
    - echo "TESTING SOME SECURITY TESTS"
    - python -m unittest discover -s ./api-application/tests/security_controller/
